import { MockAgent } from "undici";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { buildHttpApp, type App } from "@/app.js";
import { parseConfig } from "@/config/env.js";
import { createContainer, type Container } from "@/container.js";
import {
  createFakeConfigServiceGateway,
  createFakeValidationGateway,
} from "@/test/fakes.js";
import {
  acceptsAction,
  acceptsActionAndCallsBack,
} from "@/test/mock-participant.js";
import { advertisedUri } from "@/modules/session/session.service.js";
import { runOneTransaction } from "@/modules/batch/batch.driver.js";
import {
  IssuedPairTracker,
  generateOrderInputs,
} from "@/modules/batch/batch.input-generator.js";
import {
  BATCH_FIXTURE_BUILD,
  BATCH_FIXTURE_FLOW_ID,
  BATCH_FIXTURE_FLOW,
  STATION_FIRST_FLOW,
  STATION_FIRST_FLOW_ID,
} from "@/modules/batch/batch.test-fixture.js";

/**
 * `runOneTransaction`, end to end, against a scripted counterparty — both
 * roles. Everything up to the socket is real (payloads generated by the
 * fixture's own worker JS, calls dispatched through undici, callbacks arriving
 * through the actual receiver routes), exactly as `flow.loop.test.ts` proves
 * for the tool-driven loop. What is scripted is the counterparty's judgement:
 * it ACKs and calls back on cue, which is what a bounded, deterministic test
 * wants held still.
 *
 * URLs are built from `advertisedUri`/`receiverRole` rather than hand-guessed:
 * every session on one build+role shares the same callback path (see
 * `session.service.ts#advertisedUri`), so this does not need the session
 * object `runOneTransaction` creates internally and never returns.
 */

const NP = "https://np.example.com";
const config = parseConfig({ NODE_ENV: "test", LOG_LEVEL: "silent" });

let app: App;
let container: Container;
let agent: MockAgent;

function receiverUrl(mockRole: "BAP" | "BPP", action: string): string {
  const base = advertisedUri(
    container.receiverPublicUrl,
    BATCH_FIXTURE_BUILD,
    mockRole,
  );
  return `${new URL(base).pathname}/${action}`;
}

function inboundContext(
  overrides: Record<string, unknown>,
): Record<string, unknown> {
  return {
    domain: BATCH_FIXTURE_BUILD.domain,
    version: BATCH_FIXTURE_BUILD.version,
    timestamp: new Date().toISOString(),
    ttl: "PT30S",
    ...overrides,
  };
}

beforeEach(async () => {
  agent = new MockAgent();
  agent.disableNetConnect();
  container = await createContainer(config, {
    configServiceGateway: createFakeConfigServiceGateway(),
    validationGateway: createFakeValidationGateway(),
    senderDispatcher: agent,
  });
  app = await buildHttpApp(container, config);
  await app.ready();
});

afterEach(async () => {
  await app.close();
  await container.dispose();
});

describe("runOneTransaction — initiator (mock BAP)", () => {
  it("drives search -> select to COMPLETE, reading the real item id back", async () => {
    // The counterparty (a mock BPP) accepts search and calls back on_search
    // with a real catalog item id, then accepts select and calls back
    // on_select — exactly what a live seller would do. Our own receiver plays
    // BAP, so it listens on the "buyer" route regardless of which session.
    const searchCall = acceptsActionAndCallsBack(
      agent,
      NP,
      "search",
      async (payload) => {
        const ctx = (payload as { context: Record<string, string> }).context;
        await app.inject({
          method: "POST",
          url: receiverUrl("BAP", "on_search"),
          headers: { "content-type": "application/json" },
          payload: {
            context: inboundContext({
              ...ctx,
              action: "on_search",
              bap_id: ctx["bap_id"],
              bap_uri: ctx["bap_uri"],
              bpp_id: new URL(NP).host,
              bpp_uri: NP,
            }),
            message: {
              catalog: { providers: [{ items: [{ id: "real-item-42" }] }] },
            },
          },
        });
      },
    );
    const selectCall = acceptsActionAndCallsBack(
      agent,
      NP,
      "select",
      async (payload) => {
        const ctx = (payload as { context: Record<string, string> }).context;
        await app.inject({
          method: "POST",
          url: receiverUrl("BAP", "on_select"),
          headers: { "content-type": "application/json" },
          payload: {
            context: inboundContext({ ...ctx, action: "on_select" }),
            message: { order: { id: "order-1" } },
          },
        });
      },
    );

    const tracker = new IssuedPairTracker();
    const inputs = generateOrderInputs(tracker);

    const result = await runOneTransaction(
      {
        session: container.services.session,
        flow: container.services.flow,
        record: container.services.record,
        logger: container.logger,
      },
      {
        index: 0,
        role: "initiator",
        domain: BATCH_FIXTURE_BUILD.domain,
        version: BATCH_FIXTURE_BUILD.version,
        usecase: BATCH_FIXTURE_BUILD.usecase,
        flowId: BATCH_FIXTURE_FLOW_ID,
        counterpartySubscriberUrl: NP,
        inputs,
        perTransactionTimeoutMs: 15_000,
        isCancelled: () => false,
        flow: BATCH_FIXTURE_FLOW,
      },
    );

    expect(result.status).toBe("completed");
    expect(result.transaction_id).not.toBeNull();
    expect(result.item_id).toBe("real-item-42");
    expect(result.inputs).toEqual(inputs);

    // The real item id — never a hardcoded guess — is what went out on select.
    const sentSelect = selectCall.seen[0] as {
      message: { order: { items: { id: string }[] } };
    };
    expect(sentSelect.message.order.items[0]?.id).toBe("real-item-42");

    // search1 really did carry this order's own generated city_code.
    const sentSearch = searchCall.seen[0] as {
      message: { intent: { location: { city: { code: string } } } };
    };
    expect(sentSearch.message.intent.location.city.code).toBe(inputs.city_code);
  });

  it("times out rather than guessing when on_search's item id never arrives", async () => {
    acceptsAction(agent, NP, "search");

    const tracker = new IssuedPairTracker();
    const result = await runOneTransaction(
      {
        session: container.services.session,
        flow: container.services.flow,
        record: container.services.record,
        logger: container.logger,
      },
      {
        index: 1,
        role: "initiator",
        domain: BATCH_FIXTURE_BUILD.domain,
        version: BATCH_FIXTURE_BUILD.version,
        usecase: BATCH_FIXTURE_BUILD.usecase,
        flowId: BATCH_FIXTURE_FLOW_ID,
        counterpartySubscriberUrl: NP,
        inputs: generateOrderInputs(tracker),
        perTransactionTimeoutMs: 2_000,
        isCancelled: () => false,
        flow: BATCH_FIXTURE_FLOW,
      },
    );

    // No on_search ever arrives, so the wait's own deadline fires — never a
    // fabricated item id, and never an uncaught throw reaching the pool.
    expect(result.status).toBe("timed_out");
    expect(result.item_id).toBeUndefined();
  });
});

describe("runOneTransaction — listener (mock BPP)", () => {
  it("arms, watches the sequence complete, then fires the unsolicited close", async () => {
    // Our own outbound on_search/on_select — the counterparty just ACKs.
    const onSearchCall = acceptsAction(agent, NP, "on_search");
    const onSelectCall = acceptsAction(agent, NP, "on_select");
    // ...and the unsolicited close itself (wire action "on_status", per the
    // fixture's extraSequence entry — action_id names the flow step, not the
    // protocol action on the wire).
    const closeCall = acceptsAction(agent, NP, "on_status");

    const listening = runOneTransaction(
      {
        session: container.services.session,
        flow: container.services.flow,
        record: container.services.record,
        logger: container.logger,
      },
      {
        index: 0,
        role: "listener",
        domain: BATCH_FIXTURE_BUILD.domain,
        version: BATCH_FIXTURE_BUILD.version,
        usecase: BATCH_FIXTURE_BUILD.usecase,
        flowId: BATCH_FIXTURE_FLOW_ID,
        counterpartySubscriberUrl: NP,
        perTransactionTimeoutMs: 15_000,
        isCancelled: () => false,
        flow: BATCH_FIXTURE_FLOW,
      },
    );

    // Give the listener a moment to arm before the "buyer" calls — arming
    // is async (session_create + flow_start) and this is a real race with
    // whatever calls next, exactly as it would be against a live buyer.
    await new Promise((resolve) => setTimeout(resolve, 200));

    const transactionId = "listener-test-txn";
    const bapId = new URL(NP).host;

    // Our receiver plays BPP here, so it listens on the "seller" route.
    const searchRes = await app.inject({
      method: "POST",
      url: receiverUrl("BPP", "search"),
      headers: { "content-type": "application/json" },
      payload: {
        context: inboundContext({
          action: "search",
          transaction_id: transactionId,
          message_id: "msg-search",
          bap_id: bapId,
          bap_uri: NP,
        }),
        message: { intent: { location: { city: { code: "std:080" } } } },
      },
    });
    expect(searchRes.statusCode).toBe(200);

    // Auto-advance carries search -> on_search on its own; wait for it to
    // land before firing select, exactly as a real buyer would wait for the
    // catalog before selecting from it.
    await new Promise((resolve) => setTimeout(resolve, 300));

    const selectRes = await app.inject({
      method: "POST",
      url: receiverUrl("BPP", "select"),
      headers: { "content-type": "application/json" },
      payload: {
        context: inboundContext({
          action: "select",
          transaction_id: transactionId,
          message_id: "msg-select",
          bap_id: bapId,
          bap_uri: NP,
        }),
        message: { order: { items: [{ id: "real-item-42" }] } },
      },
    });
    expect(selectRes.statusCode).toBe(200);

    const result = await listening;

    expect(result.status).toBe("completed");
    expect(result.transaction_id).toBe(transactionId);
    expect(onSearchCall.seen).toHaveLength(1);
    expect(onSelectCall.seen).toHaveLength(1);
    expect(closeCall.seen).toHaveLength(1);
  });
});

describe("runOneTransaction — a flow that opens at the station search", () => {
  it("falls back to the configured serviceable stations when no catalog exists yet", async () => {
    // No prior on_search, so no business data and no bound transaction exist
    // when stations must be chosen — exactly the shape that sent the driver's
    // own generated placeholder codes onto the wire before this fixture and
    // this fix existed.
    const searchCall = acceptsActionAndCallsBack(
      agent,
      NP,
      "search",
      async (payload) => {
        const ctx = (payload as { context: Record<string, string> }).context;
        await app.inject({
          method: "POST",
          url: receiverUrl("BAP", "on_search"),
          headers: { "content-type": "application/json" },
          payload: {
            context: inboundContext({
              ...ctx,
              action: "on_search",
              bap_id: ctx["bap_id"],
              bap_uri: ctx["bap_uri"],
              bpp_id: new URL(NP).host,
              bpp_uri: NP,
            }),
            message: {},
          },
        });
      },
    );

    const tracker = new IssuedPairTracker();
    const inputs = generateOrderInputs(tracker);

    const result = await runOneTransaction(
      {
        session: container.services.session,
        flow: container.services.flow,
        record: container.services.record,
        logger: container.logger,
      },
      {
        index: 0,
        role: "initiator",
        domain: BATCH_FIXTURE_BUILD.domain,
        version: BATCH_FIXTURE_BUILD.version,
        usecase: BATCH_FIXTURE_BUILD.usecase,
        flowId: STATION_FIRST_FLOW_ID,
        counterpartySubscriberUrl: NP,
        inputs,
        perTransactionTimeoutMs: 15_000,
        isCancelled: () => false,
        flow: STATION_FIRST_FLOW,
        config: {
          itemIdsBusinessDataKey: "item_ids",
          serviceableStationCodes: ["ONLY_A", "ONLY_B"],
        },
      },
    );

    expect(result.status).toBe("completed");

    const sent = searchCall.seen[0] as {
      message: {
        intent: {
          fulfillment: {
            stops: {
              type: string;
              location: { descriptor: { code: string } };
            }[];
          };
        };
      };
    };
    const stops = sent.message.intent.fulfillment.stops;
    const start = stops.find((s) => s.type === "START")?.location.descriptor
      .code;
    const end = stops.find((s) => s.type === "END")?.location.descriptor.code;

    // The stations that actually went out are the configured, known-serviceable
    // ones — not the order's own generated GPS-derived placeholders.
    expect([start, end]).toEqual(expect.arrayContaining(["ONLY_A", "ONLY_B"]));
    expect(start).not.toBe(inputs.start_code);
  });
});
