import { mkdtemp, readFile, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { MockAgent } from "undici";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { buildHttpApp, type App } from "@/app.js";
import { parseConfig } from "@/config/env.js";
import { createContainer, type Container } from "@/container.js";
import { logger } from "@/lib/logger.js";
import { SpoolSink } from "@/modules/feedback/feedback.sink.js";
import type { IssueReport } from "@/modules/feedback/feedback.schema.js";
import type { StepOutcome } from "@/modules/flow/flow.schema.js";
import type { Session } from "@/modules/session/session.schema.js";
import {
  createFakeConfigServiceGateway,
  createFakeValidationGateway,
} from "@/test/fakes.js";
import { acceptsAction } from "@/test/mock-participant.js";
import { expectNoPii } from "@/test/pii-fixtures.js";
import { RUNNABLE_BUILD, RUNNABLE_FLOW_ID } from "@/test/runnable-config.js";

/**
 * Capture, end to end, on the real loop.
 *
 * The unit tests establish that each piece behaves; this one establishes that
 * a run which actually goes wrong produces a file on disk containing something
 * worth reading and nothing worth hiding. Both directions are real — outbound
 * over an intercepted socket, payloads generated by the config's own JavaScript
 * in a worker — and the sink is a genuine `SpoolSink` pointed at a temp
 * directory rather than a fake.
 */

const NP = "https://np.example.com";
const config = parseConfig({ NODE_ENV: "test", LOG_LEVEL: "silent" });
const quiet = logger.child({ silent: true });

let app: App;
let container: Container;
let agent: MockAgent;
let spool: SpoolSink;
let directory: string;
let session: Session;

/** A participant that refuses everything it is sent, with a real ONDC NACK. */
function nacksAction(base: string, action: string, code: string): void {
  agent
    .get(base)
    .intercept({ path: `/${action}`, method: "POST" })
    .reply(200, {
      message: { ack: { status: "NACK" } },
      // Prose that quotes a value, the way a real participant's error does.
      error: { code, message: `no account for 9876543210 on ${action}` },
    })
    .persist();
}

beforeEach(async () => {
  agent = new MockAgent();
  agent.disableNetConnect();
  directory = await mkdtemp(join(tmpdir(), "ondc-feedback-loop-"));
  spool = new SpoolSink({ directory, maxFiles: 50, logger: quiet });

  container = await createContainer(config, {
    configServiceGateway: createFakeConfigServiceGateway(),
    validationGateway: createFakeValidationGateway(),
    senderDispatcher: agent,
    feedbackSink: spool,
  });
  app = await buildHttpApp(container, config);
  await app.ready();

  session = (
    await container.services.session.createSession({
      subscriber_url: NP,
      np_type: "BPP",
      domain: RUNNABLE_BUILD.domain,
      version: RUNNABLE_BUILD.version,
      usecase: RUNNABLE_BUILD.usecase,
    })
  ).session;
});

afterEach(async () => {
  await app.close();
  await container.dispose();
  await agent.close();
});

async function spooledReports(): Promise<IssueReport[]> {
  const files = (await readdir(directory)).filter((f) => f.endsWith(".json"));
  return Promise.all(
    files.map(async (file) => {
      const body = await readFile(join(directory, file), "utf8");
      return JSON.parse(body) as IssueReport;
    }),
  );
}

describe("a run the participant refuses", () => {
  it("spools exactly one report, and it carries no payload values", async () => {
    nacksAction(NP, "search", "30001");

    await container.services.flow.start({
      sessionId: session.session_id,
      flowId: RUNNABLE_FLOW_ID,
    });
    const outcome: StepOutcome = await container.services.flow.proceed({
      sessionId: session.session_id,
      flowId: RUNNABLE_FLOW_ID,
    });

    // The exchange completed; the refusal is the result, not an error.
    expect(outcome.outcome).toBe("SENT");
    expect(outcome.ack).toBe("NACK");

    // Shutdown is what reports a run that never resolved — the model gave up,
    // or in this case never came back at all.
    await container.services.feedback.drain();

    const reports = await spooledReports();
    expect(reports).toHaveLength(1);

    const [report] = reports;
    expect(report?.incident.trigger).toBe("OUTBOUND_NACK");
    expect(report?.incident.code).toBe("30001");
    expect(report?.incident.state).toBe("UNRESOLVED");
    // Never narrated, and it shipped anyway. That is the guarantee.
    expect(report?.narration).toBeNull();

    // The participant's own message quoted a phone number at us.
    expect(JSON.stringify(report)).not.toContain("9876543210");
    expect(report?.evidence.message).toContain("<phone>");
    expectNoPii(report);
  });

  it("still carries enough to act on", async () => {
    // The counterweight to the redaction assertions: a report that survives
    // them by being empty would be worthless.
    nacksAction(NP, "search", "30001");

    await container.services.flow.start({
      sessionId: session.session_id,
      flowId: RUNNABLE_FLOW_ID,
    });
    await container.services.flow.proceed({
      sessionId: session.session_id,
      flowId: RUNNABLE_FLOW_ID,
    });
    await container.services.feedback.drain();

    const [report] = await spooledReports();

    expect(report?.build).toMatchObject({
      domain: RUNNABLE_BUILD.domain,
      version: RUNNABLE_BUILD.version,
    });
    expect(report?.flow_id).toBe(RUNNABLE_FLOW_ID);
    expect(report?.evidence.ack).toBe("NACK");
    // The journal is what shows how the run got here.
    expect(report?.journal.length).toBeGreaterThan(0);
    expect(report?.install_id).toMatch(/^inst_/);
  });

  it("tells the model, on the very next tool result", async () => {
    // The nudge rides the `events` piggyback that is already on every
    // session-scoped result; nothing else would reach the model at all.
    nacksAction(NP, "search", "30001");

    await container.services.flow.start({
      sessionId: session.session_id,
      flowId: RUNNABLE_FLOW_ID,
    });
    await container.services.flow.proceed({
      sessionId: session.session_id,
      flowId: RUNNABLE_FLOW_ID,
    });
    await container.services.feedback.settled();

    const events = await container.services.record.readEvents(
      session.session_id,
    );
    const open = events.filter((entry) => entry.kind === "ISSUE_OPEN");

    expect(open).toHaveLength(1);
    expect(open[0]?.summary).toContain("feedback_submit_report");
  });
});

describe("a run that recovers", () => {
  it("reports the recovery rather than the failure", async () => {
    // The half worth learning from. A snapshot taken when the step failed could
    // never show that the retry worked.
    acceptsAction(agent, NP, "search");

    const feedback = container.services.feedback;
    feedback.noteOutcome(session.session_id, RUNNABLE_FLOW_ID, {
      outcome: "BLOCKED",
      message: "not ready",
      reason: "requirements_not_met",
      step_key: "search",
      action: "search",
    });
    await feedback.settled();

    await container.services.flow.start({
      sessionId: session.session_id,
      flowId: RUNNABLE_FLOW_ID,
    });
    await container.services.flow.proceed({
      sessionId: session.session_id,
      flowId: RUNNABLE_FLOW_ID,
    });
    await feedback.settled();

    const [report] = await spooledReports();
    expect(report?.incident.trigger).toBe("BLOCKED");
    expect(report?.incident.state).toBe("RECOVERED");
    expect(report?.incident.duration_ms).toBeGreaterThanOrEqual(0);
  });
});
