import { MockAgent } from "undici";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import type { StepOutcome } from "@/modules/flow/flow.schema.js";
import { RUNNABLE_BUILD, RUNNABLE_FLOW_ID } from "@/test/runnable-config.js";
import { createHarness, type Harness } from "@/test/harness.js";
import { acceptsAction, type ScriptedCall } from "@/test/mock-participant.js";

/**
 * The outbound half of the loop, driven through a real MCP client against a
 * scripted participant.
 *
 * The participant is undici's `MockAgent`, so payloads really are generated by
 * the mock config's own JavaScript in a worker thread and really are POSTed —
 * only the socket is intercepted. That matters: the bugs this catches (canned
 * identity leaking into `context`, a step dispatching twice, requirements
 * blocking the wrong step) all live in the parts a stub would replace.
 */

const NP = "https://np.example.com";

let harness: Harness;
let agent: MockAgent;
let sessionId: string;
let transactionId: string;

/** The participant accepts everything, and records what it was sent. */
function acceptAll(action: string): ScriptedCall {
  return acceptsAction(agent, NP, action);
}

async function call(
  name: string,
  args: Record<string, unknown>,
): Promise<{ outcome: StepOutcome; isError: boolean }> {
  const result = await harness.client.callTool({ name, arguments: args });
  return {
    outcome: result.structuredContent as StepOutcome,
    isError: result.isError === true,
  };
}

beforeEach(async () => {
  agent = new MockAgent();
  agent.disableNetConnect();
  harness = await createHarness({ senderDispatcher: agent });

  const created = await harness.client.callTool({
    name: "session_create",
    arguments: {
      subscriber_url: NP,
      np_type: "BPP",
      domain: RUNNABLE_BUILD.domain,
      version: RUNNABLE_BUILD.version,
      usecase: RUNNABLE_BUILD.usecase,
    },
  });
  sessionId = (created.structuredContent as { session: { session_id: string } })
    .session.session_id;
});

afterEach(async () => {
  await harness.close();
  await agent.close();
});

async function startFlow(
  extra: Record<string, unknown> = {},
): Promise<Record<string, unknown>> {
  const result = await harness.client.callTool({
    name: "flow_start",
    arguments: { session_id: sessionId, flow_id: RUNNABLE_FLOW_ID, ...extra },
  });
  const output = result.structuredContent as Record<string, unknown>;
  transactionId = String(output["transaction_id"]);
  return output;
}

describe("flow_start", () => {
  it("opens a transaction and reports the first step as ours", async () => {
    const output = await startFlow();

    expect(output["mock_role"]).toBe("BAP");
    expect(String(output["callback_url"])).toBe(
      `http://127.0.0.1:3000/${RUNNABLE_BUILD.domain}/${RUNNABLE_BUILD.version}/buyer`,
    );
    expect(output["outcome"]).toMatchObject({
      outcome: "READY",
      step_key: "search_1",
      action: "search",
    });
  });

  it("refuses a flow with no published mock config", async () => {
    const result = await harness.client.callTool({
      name: "flow_start",
      arguments: { session_id: sessionId, flow_id: "does_not_exist" },
    });

    expect(result.isError).toBe(true);
    expect(result.structuredContent).toMatchObject({
      error: { code: "not_found" },
    });
  });

  it("refuses to reuse a transaction id already running", async () => {
    await startFlow({ transaction_id: "fixed-txn" });

    const result = await harness.client.callTool({
      name: "flow_start",
      arguments: {
        session_id: sessionId,
        flow_id: RUNNABLE_FLOW_ID,
        transaction_id: "fixed-txn",
      },
    });

    expect(result.isError).toBe(true);
    expect(result.structuredContent).toMatchObject({
      error: { code: "conflict" },
    });
  });
});

describe("flow_proceed — sending", () => {
  it("generates and sends the step, with this mock's own identity", async () => {
    const { seen } = acceptAll("search");
    await startFlow();

    const { outcome } = await call("flow_proceed", {
      session_id: sessionId,
      transaction_id: transactionId,
    });

    expect(outcome).toMatchObject({
      outcome: "SENT",
      action: "search",
      ack: "ACK",
      http_status: 200,
    });

    const sent = seen[0] as { context: Record<string, string> };
    // The config's canned transaction_data says bap.example.com and a fixture
    // transaction id. Neither may reach the wire.
    expect(sent.context["transaction_id"]).toBe(transactionId);
    expect(sent.context["bap_uri"]).toBe(
      `http://127.0.0.1:3000/${RUNNABLE_BUILD.domain}/${RUNNABLE_BUILD.version}/buyer`,
    );
    expect(sent.context["bap_id"]).toBe("mock.ondc-mcp.local");
    expect(sent.context["bap_uri"]).not.toContain("bap.example.com");
  });

  it("passes inputs through to the config's generator", async () => {
    const { seen } = acceptAll("search");
    await startFlow();

    await call("flow_proceed", {
      session_id: sessionId,
      transaction_id: transactionId,
      inputs: { query: "gold loan" },
    });

    expect(seen[0]).toMatchObject({
      message: { intent: { descriptor: { name: "gold loan" } } },
    });
  });

  it("records the payload and what the step saved", async () => {
    acceptAll("search");
    await startFlow();

    const { outcome } = await call("flow_proceed", {
      session_id: sessionId,
      transaction_id: transactionId,
    });

    const payload = await harness.client.callTool({
      name: "record_get_payload",
      arguments: {
        session_id: sessionId,
        payload_id: outcome.payload_id,
        jsonpath: "$.context.action",
      },
    });
    expect(payload.structuredContent).toMatchObject({
      direction: "outbound",
      payload: ["search"],
    });

    const data = await harness.client.callTool({
      name: "record_get_data",
      arguments: { session_id: sessionId, transaction_id: transactionId },
    });
    // `latestMessage_id` is injected on every save; the step also declares it.
    expect(
      (data.structuredContent as { data: Record<string, string[]> }).data[
        "latestMessage_id"
      ],
    ).toHaveLength(1);
  });

  it("waits once the next step is the participant's", async () => {
    acceptAll("search");
    await startFlow();
    await call("flow_proceed", {
      session_id: sessionId,
      transaction_id: transactionId,
    });

    const { outcome } = await call("flow_proceed", {
      session_id: sessionId,
      transaction_id: transactionId,
    });

    expect(outcome).toMatchObject({
      outcome: "WAITING",
      expected_action: "on_search",
    });
  });

  it("reports a NACK as a finding rather than a failure", async () => {
    agent
      .get(NP)
      .intercept({ path: "/search", method: "POST" })
      .reply(200, {
        message: { ack: { status: "NACK" } },
        error: { code: "30000", message: "domain not supported" },
      });
    await startFlow();

    const { outcome, isError } = await call("flow_proceed", {
      session_id: sessionId,
      transaction_id: transactionId,
    });

    expect(isError).toBe(false);
    expect(outcome).toMatchObject({ outcome: "SENT", ack: "NACK" });
    expect(outcome.ack_body).toMatchObject({ error: { code: "30000" } });
  });

  it("surfaces an unreachable participant as a tool error", async () => {
    agent
      .get(NP)
      .intercept({ path: "/search", method: "POST" })
      .replyWithError(new Error("ECONNREFUSED"));
    await startFlow();

    const { isError } = await call("flow_proceed", {
      session_id: sessionId,
      transaction_id: transactionId,
    });

    expect(isError).toBe(true);
  });
});

describe("flow_proceed — gates", () => {
  it("blocks a step whose requirements are not met", async () => {
    // `select_1` needs a providerId, which only `on_search` supplies. Reaching
    // it early must say so rather than generate a payload with a null provider.
    acceptAll("search");
    acceptAll("select");
    await startFlow();
    await call("flow_proceed", {
      session_id: sessionId,
      transaction_id: transactionId,
    });

    // Force the cursor past on_search by recording it directly.
    const records = harness.container.services.record;
    await records.appendApiEntry({
      transactionId,
      subscriberUrl: NP,
      action: "on_search",
      messageId: "m-in",
      direction: "inbound",
      timestamp: new Date(Date.now() + 1_000).toISOString(),
      body: { context: { action: "on_search" }, message: { catalog: {} } },
      ackBody: { message: { ack: { status: "ACK" } } },
    });

    const { outcome } = await call("flow_proceed", {
      session_id: sessionId,
      transaction_id: transactionId,
      inputs: { loan_amount: 50_000 },
    });

    expect(outcome).toMatchObject({
      outcome: "BLOCKED",
      reason: "requirements_not_met",
      step_key: "select_1",
    });
  });

  it("asks for input before sending a step that declares some", async () => {
    acceptAll("search");
    await startFlow();
    await call("flow_proceed", {
      session_id: sessionId,
      transaction_id: transactionId,
    });

    const records = harness.container.services.record;
    await records.appendApiEntry({
      transactionId,
      subscriberUrl: NP,
      action: "on_search",
      messageId: "m-in",
      direction: "inbound",
      timestamp: new Date(Date.now() + 1_000).toISOString(),
      body: {
        context: { action: "on_search" },
        message: { catalog: { providers: [{ id: "p1" }] } },
      },
      ackBody: { message: { ack: { status: "ACK" } } },
    });
    await records.saveBusinessData(
      transactionId,
      NP,
      {
        context: {},
        message: { catalog: { providers: [{ id: "p1" }] } },
      },
      { providerId: "$.message.catalog.providers[*].id" },
    );

    const { outcome } = await call("flow_proceed", {
      session_id: sessionId,
      transaction_id: transactionId,
    });

    expect(outcome).toMatchObject({
      outcome: "INPUT_REQUIRED",
      step_key: "select_1",
    });
    expect(outcome.inputs_required).toEqual([
      expect.objectContaining({ name: "loan_amount" }),
    ]);
  });

  it("dry_run generates a payload without putting it on the wire", async () => {
    let calls = 0;
    agent
      .get(NP)
      .intercept({ path: "/search", method: "POST" })
      .reply(200, () => {
        calls += 1;
        return { message: { ack: { status: "ACK" } } };
      })
      .persist();
    await startFlow();

    const { outcome } = await call("flow_proceed", {
      session_id: sessionId,
      transaction_id: transactionId,
      dry_run: true,
    });

    expect(outcome.outcome).toBe("DRAFTED");
    expect(calls).toBe(0);

    // The flow must not have moved: the same step is still ours to send.
    const status = await harness.client.callTool({
      name: "flow_get_status",
      arguments: { session_id: sessionId, transaction_id: transactionId },
    });
    expect(
      (status.structuredContent as { next: StepOutcome }).next,
    ).toMatchObject({ outcome: "READY", step_key: "search_1" });

    // …but the draft is readable.
    const payload = await harness.client.callTool({
      name: "record_get_payload",
      arguments: {
        session_id: sessionId,
        payload_id: outcome.payload_id,
        jsonpath: "$.context.action",
      },
    });
    expect(payload.structuredContent).toMatchObject({ payload: ["search"] });
  });

  it("rejects an unknown trigger_extra", async () => {
    await startFlow();

    const { outcome } = await call("flow_proceed", {
      session_id: sessionId,
      transaction_id: transactionId,
      trigger_extra: "nope",
    });

    expect(outcome).toMatchObject({
      outcome: "BLOCKED",
      reason: "unknown_extra",
    });
  });
});

describe("flow_get_status", () => {
  it("derives the sequence from the recorded exchanges", async () => {
    acceptAll("search");
    await startFlow();
    await call("flow_proceed", {
      session_id: sessionId,
      transaction_id: transactionId,
    });

    const result = await harness.client.callTool({
      name: "flow_get_status",
      arguments: { session_id: sessionId, transaction_id: transactionId },
    });
    const status = result.structuredContent as {
      flow_status: string;
      sequence: { key: string; status: string; actor: string }[];
      seq: number;
      next: StepOutcome;
    };

    expect(status.flow_status).toBe("IN_PROGRESS");
    expect(status.seq).toBe(1);
    expect(status.sequence.map((step) => [step.key, step.status])).toEqual([
      ["search_1", "COMPLETE"],
      ["on_search_1", "LISTENING"],
      ["select_1", "WAITING"],
      ["on_select_1", "WAITING"],
    ]);
    // Actor is stated relative to the mock, which is what the loop acts on.
    expect(status.sequence[0]?.actor).toBe("mock");
    expect(status.sequence[1]?.actor).toBe("np");
    expect(status.next.outcome).toBe("WAITING");

    const text = (result.content as { text: string }[])[0]?.text ?? "";
    expect(text).toContain("search_1");
    expect(text).toContain("WAITING");
  });

  it("reports NOT_STARTED before anything has been exchanged", async () => {
    await startFlow();

    const result = await harness.client.callTool({
      name: "flow_get_status",
      arguments: { session_id: sessionId, transaction_id: transactionId },
    });

    expect(result.structuredContent).toMatchObject({
      flow_status: "NOT_STARTED",
    });
  });

  it("reports an unknown transaction as not found", async () => {
    const result = await harness.client.callTool({
      name: "flow_get_status",
      arguments: { session_id: sessionId, transaction_id: "nope" },
    });

    expect(result.isError).toBe(true);
    expect(result.structuredContent).toMatchObject({
      error: { code: "not_found" },
    });
  });
});
