import { MockAgent } from "undici";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import type { StepOutcome } from "@/modules/flow/flow.schema.js";
import { RUNNABLE_BUILD, RUNNABLE_FLOW_ID } from "@/test/runnable-config.js";
import { createHarness, type Harness } from "@/test/harness.js";
import { acceptsAction, type ScriptedCall } from "@/test/mock-participant.js";

/**
 * The outbound half of the loop, driven through a real MCP client against a
 * scripted participant.
 *
 * The participant is undici's `MockAgent`, so payloads really are generated by
 * the mock config's own JavaScript in a worker thread and really are POSTed —
 * only the socket is intercepted. That matters: the bugs this catches (canned
 * identity leaking into `context`, a step dispatching twice, requirements
 * blocking the wrong step) all live in the parts a stub would replace.
 */

const NP = "https://np.example.com";

let harness: Harness;
let agent: MockAgent;
let sessionId: string;
let transactionId: string;

/** The participant accepts everything, and records what it was sent. */
function acceptAll(action: string): ScriptedCall {
  return acceptsAction(agent, NP, action);
}

async function call(
  name: string,
  args: Record<string, unknown>,
): Promise<{ outcome: StepOutcome; isError: boolean }> {
  const result = await harness.client.callTool({ name, arguments: args });
  return {
    outcome: result.structuredContent as StepOutcome,
    isError: result.isError === true,
  };
}

beforeEach(async () => {
  agent = new MockAgent();
  agent.disableNetConnect();
  harness = await createHarness({ senderDispatcher: agent });

  const created = await harness.client.callTool({
    name: "session_create",
    arguments: {
      subscriber_url: NP,
      np_type: "BPP",
      domain: RUNNABLE_BUILD.domain,
      version: RUNNABLE_BUILD.version,
      usecase: RUNNABLE_BUILD.usecase,
    },
  });
  sessionId = (created.structuredContent as { session: { session_id: string } })
    .session.session_id;
});

afterEach(async () => {
  await harness.close();
  await agent.close();
});

async function startFlow(
  extra: Record<string, unknown> = {},
): Promise<Record<string, unknown>> {
  const result = await harness.client.callTool({
    name: "flow_start",
    arguments: { session_id: sessionId, flow_id: RUNNABLE_FLOW_ID, ...extra },
  });
  // Deliberately not read off the output: a run that has put nothing on the
  // wire has no transaction id, and `proceed` is what mints one.
  transactionId = "";
  return result.structuredContent as Record<string, unknown>;
}

/** Advance the run, naming it by flow, and keep whatever id it reports. */
async function proceed(
  extra: Record<string, unknown> = {},
): Promise<{ outcome: StepOutcome; isError: boolean }> {
  const result = await call("flow_proceed", {
    session_id: sessionId,
    flow_id: RUNNABLE_FLOW_ID,
    ...extra,
  });
  if (typeof result.outcome?.transaction_id === "string") {
    transactionId = result.outcome.transaction_id;
  }
  return result;
}

describe("flow_start", () => {
  it("opens a transaction and reports the first step as ours", async () => {
    const output = await startFlow();

    expect(output["mock_role"]).toBe("BAP");
    expect(String(output["callback_url"])).toBe(
      `http://127.0.0.1:3000/${RUNNABLE_BUILD.domain}/${RUNNABLE_BUILD.version}/buyer`,
    );
    expect(output["outcome"]).toMatchObject({
      outcome: "READY",
      step_key: "search_1",
      action: "search",
    });
  });

  it("refuses a flow with no published mock config", async () => {
    const result = await harness.client.callTool({
      name: "flow_start",
      arguments: { session_id: sessionId, flow_id: "does_not_exist" },
    });

    expect(result.isError).toBe(true);
    expect(result.structuredContent).toMatchObject({
      error: { code: "not_found" },
    });
  });

  it("mints nothing and persists nothing", async () => {
    const output = await startFlow();

    // The id belongs to whoever sends the flow's first action. Here that is
    // this mock, and it has not sent it yet.
    expect(output["transaction_id"]).toBeNull();

    const ids =
      await harness.container.services.record.listTransactionIds(sessionId);
    expect(ids).toEqual([]);
  });

  it("refuses to resume a transaction that does not exist", async () => {
    // An explicit id means "resume that transaction". Conjuring a record for
    // an id the caller invented is exactly what this change removes: it would
    // put a transaction on the books that no payload ever referenced.
    const result = await harness.client.callTool({
      name: "flow_start",
      arguments: {
        session_id: sessionId,
        flow_id: RUNNABLE_FLOW_ID,
        transaction_id: "never-existed",
      },
    });

    expect(result.isError).toBe(true);
    expect(result.structuredContent).toMatchObject({
      error: { code: "not_found" },
    });
  });

  it("resumes a run that is already going, rather than conflicting", async () => {
    acceptAll("search");
    await startFlow();
    const { outcome } = await proceed();
    expect(outcome.outcome).toBe("SENT");
    const minted = transactionId;

    const again = await startFlow();

    expect(again["transaction_id"]).toBe(minted);
    expect(again["outcome"]).toMatchObject({ outcome: "WAITING" });
  });
});

describe("flow_proceed — sending", () => {
  it("generates and sends the step, with this mock's own identity", async () => {
    const { seen } = acceptAll("search");
    await startFlow();

    const { outcome } = await proceed();

    expect(outcome).toMatchObject({
      outcome: "SENT",
      action: "search",
      ack: "ACK",
      http_status: 200,
    });

    const sent = seen[0] as { context: Record<string, string> };
    // The config's canned transaction_data says bap.example.com and a fixture
    // transaction id. Neither may reach the wire.
    expect(sent.context["transaction_id"]).toBe(transactionId);
    expect(sent.context["bap_uri"]).toBe(
      `http://127.0.0.1:3000/${RUNNABLE_BUILD.domain}/${RUNNABLE_BUILD.version}/buyer`,
    );
    expect(sent.context["bap_id"]).toBe("mock.ondc-mcp.local");
    expect(sent.context["bap_uri"]).not.toContain("bap.example.com");
  });

  it("seeds identity as lists, because configs index it [0]", async () => {
    /*
     * Regression: `#seedIdentity` wrote bare strings.
     *
     * Everything else in `sessionData` arrives through `saveData`, which runs
     * `jsonpath.query` and always yields a list, so published configs index
     * identity in place — live TRV11 has
     * `context.bpp_id = sessionData?.bppId[0]`. A bare string does not throw
     * there; `[0]` is its first character, so `"mock.ondc-mcp.local"` reaches
     * a third party's wire as `"m"`.
     *
     * This is the flow's first action, which is exactly when it bites: nothing
     * has been saved, so all four keys are seeds rather than saves. The same
     * hole opens later for any field the participant omits, because an omitted
     * field saves as `[]` and falls back to the seed.
     */
    const { seen } = acceptAll("search");
    await startFlow();
    await proceed();

    const sent = seen[0] as {
      message: { intent: { identity: Record<string, string> } };
    };
    const identity = sent.message.intent.identity;

    expect(identity["bap_id"]).toBe("mock.ondc-mcp.local");
    expect(identity["bap_uri"]).toBe(
      `http://127.0.0.1:3000/${RUNNABLE_BUILD.domain}/${RUNNABLE_BUILD.version}/buyer`,
    );
    // The mock is the BAP here, so the BPP half is the participant — seeded as
    // a fallback until its own payloads say otherwise, and a list either way.
    expect(identity["bpp_id"]).toBe("np.example.com");
    expect(identity["bpp_uri"]).toBe(NP);
  });

  it("passes inputs through to the config's generator", async () => {
    const { seen } = acceptAll("search");
    await startFlow();

    await proceed({ inputs: { query: "gold loan" } });

    expect(seen[0]).toMatchObject({
      message: { intent: { descriptor: { name: "gold loan" } } },
    });
  });

  it("records the payload and what the step saved", async () => {
    acceptAll("search");
    await startFlow();

    const { outcome } = await proceed();

    const payload = await harness.client.callTool({
      name: "record_get_payload",
      arguments: {
        session_id: sessionId,
        payload_id: outcome.payload_id,
        jsonpath: "$.context.action",
      },
    });
    expect(payload.structuredContent).toMatchObject({
      direction: "outbound",
      payload: ["search"],
    });

    const data = await harness.client.callTool({
      name: "record_get_data",
      arguments: { session_id: sessionId, transaction_id: transactionId },
    });
    // `latestMessage_id` is injected on every save; the step also declares it.
    expect(
      (data.structuredContent as { data: Record<string, string[]> }).data[
        "latestMessage_id"
      ],
    ).toHaveLength(1);
  });

  it("waits once the next step is the participant's", async () => {
    acceptAll("search");
    await startFlow();
    await proceed();

    const { outcome } = await proceed();

    expect(outcome).toMatchObject({
      outcome: "WAITING",
      expected_action: "on_search",
    });
  });

  it("reports a NACK as a finding rather than a failure", async () => {
    agent
      .get(NP)
      .intercept({ path: "/search", method: "POST" })
      .reply(200, {
        message: { ack: { status: "NACK" } },
        error: { code: "30000", message: "domain not supported" },
      });
    await startFlow();

    const { outcome, isError } = await proceed();

    expect(isError).toBe(false);
    expect(outcome).toMatchObject({ outcome: "SENT", ack: "NACK" });
    expect(outcome.ack_body).toMatchObject({ error: { code: "30000" } });
  });

  it("surfaces an unreachable participant as a tool error", async () => {
    agent
      .get(NP)
      .intercept({ path: "/search", method: "POST" })
      .replyWithError(new Error("ECONNREFUSED"));
    await startFlow();

    const { isError } = await proceed();

    expect(isError).toBe(true);
  });
});

describe("flow_proceed — gates", () => {
  it("blocks a step whose requirements are not met", async () => {
    // `select_1` needs a providerId, which only `on_search` supplies. Reaching
    // it early must say so rather than generate a payload with a null provider.
    acceptAll("search");
    acceptAll("select");
    await startFlow();
    await proceed();

    // Force the cursor past on_search by recording it directly.
    const records = harness.container.services.record;
    await records.appendApiEntry({
      transactionId,
      subscriberUrl: NP,
      action: "on_search",
      messageId: "m-in",
      direction: "inbound",
      timestamp: new Date(Date.now() + 1_000).toISOString(),
      body: { context: { action: "on_search" }, message: { catalog: {} } },
      ackBody: { message: { ack: { status: "ACK" } } },
    });

    const { outcome } = await proceed({ inputs: { loan_amount: 50_000 } });

    expect(outcome).toMatchObject({
      outcome: "BLOCKED",
      reason: "requirements_not_met",
      step_key: "select_1",
    });
  });

  it("asks for input before sending a step that declares some", async () => {
    acceptAll("search");
    await startFlow();
    await proceed();

    const records = harness.container.services.record;
    await records.appendApiEntry({
      transactionId,
      subscriberUrl: NP,
      action: "on_search",
      messageId: "m-in",
      direction: "inbound",
      timestamp: new Date(Date.now() + 1_000).toISOString(),
      body: {
        context: { action: "on_search" },
        message: { catalog: { providers: [{ id: "p1" }] } },
      },
      ackBody: { message: { ack: { status: "ACK" } } },
    });
    await records.saveBusinessData(
      transactionId,
      NP,
      {
        context: {},
        message: { catalog: { providers: [{ id: "p1" }] } },
      },
      { providerId: "$.message.catalog.providers[*].id" },
    );

    const { outcome } = await proceed();

    expect(outcome).toMatchObject({
      outcome: "INPUT_REQUIRED",
      step_key: "select_1",
    });
    // The keys to send, not the raw declaration — see catalog.inputs.ts.
    expect(outcome.inputs_required).toMatchObject({
      fields: [expect.objectContaining({ name: "loan_amount" })],
    });
    expect(outcome.inputs_required?.note).toMatch(/flat object/);
  });

  it("dry_run generates a payload without putting it on the wire", async () => {
    let calls = 0;
    agent
      .get(NP)
      .intercept({ path: "/search", method: "POST" })
      .reply(200, () => {
        calls += 1;
        return { message: { ack: { status: "ACK" } } };
      })
      .persist();
    await startFlow();

    const { outcome } = await proceed({ dry_run: true });

    expect(outcome.outcome).toBe("DRAFTED");
    expect(calls).toBe(0);

    // The flow must not have moved: the same step is still ours to send.
    const status = await harness.client.callTool({
      name: "flow_get_status",
      arguments: { session_id: sessionId, flow_id: RUNNABLE_FLOW_ID },
    });
    expect(
      (status.structuredContent as { next: StepOutcome }).next,
    ).toMatchObject({ outcome: "READY", step_key: "search_1" });

    // …but the draft is readable.
    const payload = await harness.client.callTool({
      name: "record_get_payload",
      arguments: {
        session_id: sessionId,
        payload_id: outcome.payload_id,
        jsonpath: "$.context.action",
      },
    });
    expect(payload.structuredContent).toMatchObject({ payload: ["search"] });
  });

  it("rejects an unknown trigger_extra", async () => {
    await startFlow();

    const { outcome } = await proceed({ trigger_extra: "nope" });

    expect(outcome).toMatchObject({
      outcome: "BLOCKED",
      reason: "unknown_extra",
    });
  });
});

describe("flow_proceed — minting the transaction id", () => {
  it("opens the transaction under the id that actually went on the wire", async () => {
    const { seen } = acceptAll("search");
    await startFlow();

    const { outcome } = await proceed();

    const sent = seen[0] as { context: Record<string, string> };
    expect(outcome.transaction_id).toBe(sent.context["transaction_id"]);

    // …and that is the id the record is keyed on, not some earlier guess.
    const record = await harness.container.services.record.requireTransaction(
      sent.context["transaction_id"] as string,
      NP,
    );
    expect(record.flowId).toBe(RUNNABLE_FLOW_ID);

    const ids =
      await harness.container.services.record.listTransactionIds(sessionId);
    expect(ids).toEqual([sent.context["transaction_id"]]);
  });

  it("mints nothing on a dry run, because nothing was sent", async () => {
    let calls = 0;
    agent
      .get(NP)
      .intercept({ path: "/search", method: "POST" })
      .reply(200, () => {
        calls += 1;
        return { message: { ack: { status: "ACK" } } };
      })
      .persist();
    await startFlow();

    const { outcome } = await proceed({ dry_run: true });

    expect(outcome.outcome).toBe("DRAFTED");
    expect(outcome.transaction_id).toBeUndefined();
    expect(calls).toBe(0);

    // A drafted payload was never on the wire, so the flow's first action is
    // still unspoken for and no transaction exists.
    const ids =
      await harness.container.services.record.listTransactionIds(sessionId);
    expect(ids).toEqual([]);

    // Sending it for real afterwards is what finally mints one.
    const sent = await proceed();
    expect(sent.outcome.outcome).toBe("SENT");
    expect(sent.outcome.transaction_id).toBeTypeOf("string");
  });

  it("does not let two concurrent calls both mint and both send", async () => {
    // An unbound run gets a fresh placeholder id on every load, so the WORKING
    // marker cannot be filed under it — both callers would take a lock of
    // their own and the flow's first action would go out twice, to a third
    // party. They contend on the run instead.
    let calls = 0;
    agent
      .get(NP)
      .intercept({ path: "/search", method: "POST" })
      .reply(200, () => {
        calls += 1;
        return { message: { ack: { status: "ACK" } } };
      })
      .persist();
    await startFlow();

    const [a, b] = await Promise.all([
      call("flow_proceed", {
        session_id: sessionId,
        flow_id: RUNNABLE_FLOW_ID,
      }),
      call("flow_proceed", {
        session_id: sessionId,
        flow_id: RUNNABLE_FLOW_ID,
      }),
    ]);

    // Serialised, so the second caller sees a flow that has already moved on
    // rather than a second chance to send the same step.
    const outcomes = [a?.outcome.outcome, b?.outcome.outcome].sort();
    expect(outcomes).toEqual(["SENT", "WAITING"]);
    expect(calls).toBe(1);
    expect(
      await harness.container.services.record.listTransactionIds(sessionId),
    ).toHaveLength(1);
  });

  it("persists nothing when the step is blocked before it can generate", async () => {
    // `select_1` needs a providerId. A BLOCKED step put no payload on the
    // wire, so it must leave no transaction behind either.
    acceptAll("search");
    await startFlow();
    await proceed();
    const minted = transactionId;

    const records = harness.container.services.record;
    await records.appendApiEntry({
      transactionId: minted,
      subscriberUrl: NP,
      action: "on_search",
      messageId: "m-in",
      direction: "inbound",
      timestamp: new Date(Date.now() + 1_000).toISOString(),
      body: { context: { action: "on_search" }, message: { catalog: {} } },
      ackBody: { message: { ack: { status: "ACK" } } },
    });

    const { outcome } = await proceed({ inputs: { loan_amount: 1 } });

    expect(outcome).toMatchObject({ reason: "requirements_not_met" });
    expect(await records.listTransactionIds(sessionId)).toEqual([minted]);
  });
});

describe("flow_get_status", () => {
  it("derives the sequence from the recorded exchanges", async () => {
    acceptAll("search");
    await startFlow();
    await proceed();

    const result = await harness.client.callTool({
      name: "flow_get_status",
      arguments: { session_id: sessionId, flow_id: RUNNABLE_FLOW_ID },
    });
    const status = result.structuredContent as {
      flow_status: string;
      sequence: { key: string; status: string; actor: string }[];
      seq: number;
      next: StepOutcome;
    };

    expect(status.flow_status).toBe("IN_PROGRESS");
    expect(status.seq).toBe(1);
    expect(status.sequence.map((step) => [step.key, step.status])).toEqual([
      ["search_1", "COMPLETE"],
      ["on_search_1", "LISTENING"],
      ["select_1", "WAITING"],
      ["on_select_1", "WAITING"],
    ]);
    // Actor is stated relative to the mock, which is what the loop acts on.
    expect(status.sequence[0]?.actor).toBe("mock");
    expect(status.sequence[1]?.actor).toBe("np");
    expect(status.next.outcome).toBe("WAITING");

    const text = (result.content as { text: string }[])[0]?.text ?? "";
    expect(text).toContain("search_1");
    expect(text).toContain("WAITING");
  });

  it("reports NOT_STARTED before anything has been exchanged", async () => {
    await startFlow();

    const result = await harness.client.callTool({
      name: "flow_get_status",
      arguments: { session_id: sessionId, flow_id: RUNNABLE_FLOW_ID },
    });

    expect(result.structuredContent).toMatchObject({
      flow_status: "NOT_STARTED",
      // Nothing has crossed the wire, so nobody has minted an id yet.
      transaction_id: null,
    });
  });

  it("reports an unknown transaction as not found", async () => {
    const result = await harness.client.callTool({
      name: "flow_get_status",
      arguments: { session_id: sessionId, transaction_id: "nope" },
    });

    expect(result.isError).toBe(true);
    expect(result.structuredContent).toMatchObject({
      error: { code: "not_found" },
    });
  });
});

describe("flow_restart", () => {
  async function restart(
    extra: Record<string, unknown> = {},
  ): Promise<{
    output: Record<string, unknown>;
    text: string;
    isError: boolean;
  }> {
    const result = await harness.client.callTool({
      name: "flow_restart",
      arguments: { session_id: sessionId, flow_id: RUNNABLE_FLOW_ID, ...extra },
    });
    return {
      output: result.structuredContent as Record<string, unknown>,
      text: (result.content as { text: string }[])[0]?.text ?? "",
      isError: result.isError === true,
    };
  }

  it("hands back a run the model can drive straight away", async () => {
    acceptAll("search");
    await startFlow();
    await proceed();
    const firstTxn = transactionId;

    const { output, text } = await restart({ reason: "search went out wrong" });

    expect(output).toMatchObject({
      transaction_id: null,
      abandoned_transaction_id: firstTxn,
      attempt: 2,
      flow_id: RUNNABLE_FLOW_ID,
    });
    // The next step is ours again, and the rendering says which tool to call.
    expect(output["outcome"]).toMatchObject({
      outcome: "READY",
      step_key: "search_1",
    });
    expect(text).toContain("attempt 2");
    expect(text).toContain("flow_proceed");
  });

  it("re-arms only this run, leaving the session's other flows listening", async () => {
    // Restart clears expectations per flow. Session-wide would take down a
    // sibling flow's listener and leave it waiting on an endpoint that had
    // quietly stopped accepting its callback.
    const scope = {
      domain: RUNNABLE_BUILD.domain,
      version: RUNNABLE_BUILD.version,
      role: "buyer",
    } as const;
    const records = harness.container.services.record;

    await startFlow();
    await records.armExpectation(scope, {
      sessionId,
      flowId: "some_other_flow",
      expectedAction: "on_status",
      subscriberUrl: NP,
      autoAdvance: false,
    });

    await restart();

    const armed = await records.expectationsForSession(scope, sessionId);
    expect(armed.map((entry) => entry.flowId)).toEqual(["some_other_flow"]);
  });

  it("names flow_start when there is no run to restart", async () => {
    const { output, isError } = await restart();

    expect(isError).toBe(true);
    expect(output).toMatchObject({
      error: { code: "not_found", details: { hint: expect.any(String) } },
    });
    expect(
      String((output["error"] as { details: { hint: string } }).details.hint),
    ).toContain("flow_start");
  });

  it("refuses to resume an attempt it has written off", async () => {
    // The hole this closes: rebinding the run to a sealed transaction would
    // undo the restart and strand the run on the history it was escaping.
    acceptAll("search");
    await startFlow();
    await proceed();
    const firstTxn = transactionId;
    await restart();

    const result = await harness.client.callTool({
      name: "flow_start",
      arguments: {
        session_id: sessionId,
        flow_id: RUNNABLE_FLOW_ID,
        transaction_id: firstTxn,
      },
    });

    expect(result.isError).toBe(true);
    expect(result.structuredContent).toMatchObject({
      error: { code: "conflict" },
    });
  });
});
